//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonuri_Stocuri
    {
        public int Bon_id { get; set; }
        public int Stoc_id { get; set; }
        public string Produs_nume { get; set; }
        public int Cantitate { get; set; }
        public int Pret { get; set; }
    
        public virtual Bonuri Bonuri { get; set; }
        public virtual Stocuri Stocuri { get; set; }
    }
}
