//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonuri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bonuri()
        {
            this.Bonuri_Stocuri = new HashSet<Bonuri_Stocuri>();
        }
    
        public int Bon_id { get; set; }
        public System.DateTime Data_eliberare { get; set; }
        public string Casier { get; set; }
        public int Suma_incasata { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bonuri_Stocuri> Bonuri_Stocuri { get; set; }
    }
}
