//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SupermarketEntities : DbContext
    {
        public SupermarketEntities()
            : base("name=SupermarketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bonuri> Bonuri { get; set; }
        public virtual DbSet<Bonuri_Stocuri> Bonuri_Stocuri { get; set; }
        public virtual DbSet<Categorie> Categorie { get; set; }
        public virtual DbSet<Producator> Producator { get; set; }
        public virtual DbSet<Produs> Produs { get; set; }
        public virtual DbSet<Stocuri> Stocuri { get; set; }
        public virtual DbSet<Utilizator> Utilizator { get; set; }
    }
}
