//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produs()
        {
            this.Stocuri = new HashSet<Stocuri>();
        }
    
        public int Produs_id { get; set; }
        public string Produs_nume { get; set; }
        public int Cod_bare { get; set; }
        public int Categorie_id { get; set; }
        public int Producator_id { get; set; }
        public bool Active { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        public virtual Producator Producator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stocuri> Stocuri { get; set; }
    }
}
