//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stocuri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stocuri()
        {
            this.Bonuri_Stocuri = new HashSet<Bonuri_Stocuri>();
        }
    
        public int Stoc_id { get; set; }
        public int Cantitate { get; set; }
        public string Unitate_masura { get; set; }
        public System.DateTime Data_aprovizionare { get; set; }
        public System.DateTime Data_expirare { get; set; }
        public int Pret_achizitie { get; set; }
        public int Pret_vanzare { get; set; }
        public int Produs_id { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bonuri_Stocuri> Bonuri_Stocuri { get; set; }
        public virtual Produs Produs { get; set; }
    }
}
