//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilizator
    {
        public int Utilizator_id { get; set; }
        public string Nume { get; set; }
        public string Parola { get; set; }
        public string Tip { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
